services:
  mariadb:
    image: mariadb:11.4
    container_name: simple-bank-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: simplebank
      MARIADB_USER: simplebankuser
      MARIADB_PASSWORD: simplebankpass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - simple-bank-net
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_INSTANA_REPORT_URL=https://eum-orange-saas.instana.io
        - NEXT_PUBLIC_INSTANA_EUM_KEY=XGKoMnXoTKOROE_ZUYmdpw
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
    image: simple-bank-website:latest
    container_name: simple-bank-website
    ports:
      - "80:8080"
    environment:
      - NEXT_PUBLIC_INSTANA_REPORT_URL=https://eum-orange-saas.instana.io
      - NEXT_PUBLIC_INSTANA_EUM_KEY=XGKoMnXoTKOROE_ZUYmdpw
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - simple-bank-net
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: simple-bank-backend:latest
    container_name: simple-bank-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/simplebank?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: simplebankuser
      SPRING_DATASOURCE_PASSWORD: simplebankpass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: simplebankuser
      SPRING_RABBITMQ_PASSWORD: simplebankpass
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: unless-stopped
    networks:
      - simple-bank-net
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: simple-bank-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: simplebankuser
      RABBITMQ_DEFAULT_PASS: simplebankpass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - simple-bank-net
  consumer:
    build: ./consumer
    container_name: simple-bank-consumer
    environment:
      RABBITMQ_URL: amqp://simplebankuser:simplebankpass@rabbitmq:5672
      DB_HOST: mariadb
      DB_USER: simplebankuser
      DB_PASS: simplebankpass
      DB_NAME: simplebank
    depends_on:
      - rabbitmq
      - mariadb
    restart: unless-stopped
    networks:
      - simple-bank-net
volumes:
  mariadb_data:
  rabbitmq_data:
networks:
  simple-bank-net:
    driver: bridge
